twilio: # Twilio gateway configuration
  accountId: 
  accountToken: 
  numbers: # Numbers allocated in Twilio
    - # First number
    - # Second number
    - # Third number
    - # ...
    - # Nth number
  messagingServicesId: 
  localDomain: # Domain Twilio can connect back to for calls. Should be domain of your service.

push:
  queueSize: # Size of push pending queue

redphone:
  authKey: # Deprecated

turn: # TURN server configuration
  secret: # TURN server secret
  uris:
    - stun:yourdomain:80
    - stun:yourdomain.com:443
    - turn:yourdomain:443?transport=udp
    - turn:etc.com:80?transport=udp

cache: # Redis server configuration for cache cluster
  url:

directory: # Redis server configuration for directory cluster
  url:

messageStore: # Postgresql database configuration for message store
  driverClass: org.postgresql.Driver
  user:
  password:
  url:

attachments: # AWS S3 configuration
  accessKey:
  accessSecret:
  bucket:

profiles: # AWS S3 configuration
  accessKey:
  accessSecret:
  bucket:
  region:

database: # Postgresql database configuration
  driverClass: org.postgresql.Driver
  user:
  password:
  url:

apn: # Apple Push Notifications configuration
  bundleId:
  pushCertificate:
  pushKey:

gcm: # GCM Configuration
  senderId:
  apiKey:
